In [81]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Titanic-Dataset.csv")

##Количество пустых ячеек
print('Количество пустых ячеек: ')
print(df.isna().sum())

##Заполняем пустые ячейки
print()
print('Заполняем пустые ячейки..... ')
df.loc[df['Cabin'].isna(), 'Cabin'] = 'NotFound'
df.loc[df['Age'].isna(), 'Age'] = df['Age'].max()/2
df.loc[df['Embarked'].isna(), 'Embarked'] = 'N'
print()

##Количество пустых ячеек после заполнения
print('Количество пустых ячеек после заполнения: ')
print(df.isna().sum())

##Аналитика
print()
print('Аналитика: ')
print(' 1. Количество уникальных значений')
print(df.nunique())

print()
print(' 2.1 Минимальное значение')
print(df[["PassengerId", "Survived", "Pclass", "Age", "SibSp", "Parch", "Fare"]].min())

print()
print(' 2.2 Максимальное значение')
print(df[["PassengerId", "Survived", "Pclass", "Age", "SibSp", "Parch", "Fare"]].max())

Количество пустых ячеек:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Заполняем пустые ячейки.....

Количество пустых ячеек после заполнения:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

Аналитика:
 1. Количество уникальных значений
PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          148
Embarked         4
dtype: int64

 2.1 Минимальное значение
PassengerId    1.00
Survived       0.00
Pclass         1.00
Age            0.42
SibSp          0.00
Parch          0.00
Fare           0.00
dtype: float64

 2.2 Максимальное значение
PassengerId    891.0000
Survived         1.0000
Pclass           3.0000
Age             80.0000
SibSp            8.0000
Parch            6.0000
Fare           512.3292
dtype: float64